# Generated by Django 4.2.30 on 2026-04-20 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_user_id_73c422_idx',
            old_name='audit_logs_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_model_n_da6855_idx',
            old_name='audit_logs_model_name_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_timesta_423be6_idx',
            old_name='audit_logs_timestamp_idx',
        ),
    ]
